### ISSUE TITLE
[suggestion] convert automatically 

### ISSUE THREAD

**Issue by 2edff206** [kosinix/ametrican#1]
Hello,

The extension is working great, but maybe you could add an option to convert everything in the webpage automatically, and maybe underline it and show the original version when hovering ?

Thanks a lot

**Comment by kosinix** [comment]
Whoa! I just published this add-on and there is an issue already? You probably work at..  *wink*

One thing I dont like about converting everything is the performance hit of scanning and changing the entire dom. I'd rather have it selection based. But, maybe in succeeding versions if their is a demand for it or if the add-on got some traction. I just wrote this up quickly a few hours ago to scratch an itch. :-)

Thank you for reaching out and I appreciate your interest!

**Comment by 2edff206** [comment]
I was browsing a website this morning with weights in lbs, I thought "i wish there was an extension to automatically convert these" and looked it up on Google. I couldn't believe you uploaded it only 20mins ago I thought it was a bug haha !!
Thanks

**Comment by kosinix** [comment]
Oh I see. that is quite funny. haha

btw, other users have requested the same feature, so i'll add this up in the next versions.
Cheers

**Comment by kosinix** [comment]
Hey,
You can now convert entire page and highlight the changed text. Its not yet approved in mozilla add-ons page but you can download it here directly.
