### ISSUE TITLE
Erroneously converts some value

### ISSUE THREAD

**Issue by haarp** [kosinix/ametrican#17]
On [this page](http://www.spudfiles.com/spud_wiki/index.php?title=12_gram_CO2_cartridge#Pressure), the following text appears:

    Below 87.8°F, a 12 gram CO2 cartridge contains a mixture of liquid and gaseous CO2 in equilibrium.

This addon somehow converts the '2' in 'CO2' to centimeters?

**Comment by t-gebauer** [comment]
Fixed in https://github.com/t-gebauer/ametrican/commit/dc07854156fb9e6ed63a061743e10f88c17b50d6

**Comment by haarp** [comment]
That was quick, thanks!
