### ISSUE TITLE
Missing mph conversion

### ISSUE THREAD

**Issue by mcarton** [kosinix/ametrican#7]
Muricans! use such units as "miles per hour"/"mph" which should be converted to proper km/h.

**Comment by t-gebauer** [comment]
"mi/h" and "miles per hour" should already be correctly converted as they are recognized as "mi" and "miles".

**Comment by mcarton** [comment]
But the most common abbreviation is "mph", so the extention should know about it.

**Comment by kosinix** [comment]
Fixed by #9 thanks to @t-gebauer
