### ISSUE TITLE
Missing short/long ton conversion

### ISSUE THREAD

**Issue by mcarton** [kosinix/ametrican#8]
These should be converted to metric ton/tonne.

**Comment by kosinix** [comment]
There is no simple way to differentiate short and long ton without leaning on natural language processing. Will address this issue using a context menu based solution (select > right click > open converter) in the future.

**Comment by mcarton** [comment]
I don't understand, why would converting "5 short ton" be more complicated than converting "5 feet"?

**Comment by kosinix** [comment]
Depending on the sentence 5 ton could be UK or US tons

**Comment by mcarton** [comment]
Sure, but I created this issue after reading an article that explicitly used "short ton". The extension could easily handle that case.

**Comment by kosinix** [comment]
Short ton, long ton now added. thanks @mcarton and @t-gebauer
